// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_format
std::string my_format(int sign, unsigned int p, unsigned int q, std::vector<unsigned int> nums);
RcppExport SEXP _pqnumber_my_format(SEXP signSEXP, SEXP pSEXP, SEXP qSEXP, SEXP numsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type sign(signSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    Rcpp::traits::input_parameter< std::vector<unsigned int> >::type nums(numsSEXP);
    rcpp_result_gen = Rcpp::wrap(my_format(sign, p, q, nums));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pqnumber_my_format", (DL_FUNC) &_pqnumber_my_format, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_pqnumber(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
